import Link from "next/link";

export default function PrivacyPage() {
  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>

      <div className="prose prose-slate dark:prose-invert max-w-none">
        <p className="text-muted-foreground mb-8">
          Last updated: November 28, 2025
        </p>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Introduction</h2>
          <p className="mb-4">
            Pound of Cure LLC (&quot;Write Great Notes,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) is committed to protecting your privacy and the privacy of your patients. This Privacy Policy describes how we collect, use, disclose, and safeguard information when you use our AI-powered clinical documentation platform.
          </p>
          <p className="mb-4">
            We are a HIPAA-compliant service provider and take our obligations under the Health Insurance Portability and Accountability Act seriously. We will enter into a Business Associate Agreement (BAA) with covered entities as required.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Information We Collect</h2>
          
          <h3 className="text-xl font-semibold mb-3">Account Information</h3>
          <p className="mb-4">
            When you create an account, we collect your name, email address, practice information, and payment details for subscription billing.
          </p>

          <h3 className="text-xl font-semibold mb-3">Audio and Transcription Data</h3>
          <p className="mb-4">
            Our service records and transcribes clinical encounters to generate documentation. This may include Protected Health Information (PHI). Audio recordings are processed in real-time and are not permanently stored after transcription is complete unless you explicitly choose to save them.
          </p>

          <h3 className="text-xl font-semibold mb-3">Generated Notes</h3>
          <p className="mb-4">
            Clinical notes generated by our AI are stored securely and associated with your account. You maintain full ownership and control of all generated content.
          </p>

          <h3 className="text-xl font-semibold mb-3">Usage Data</h3>
          <p className="mb-4">
            We collect information about how you interact with our service, including features used, time spent, and error reports. This helps us improve our service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">How We Use Your Information</h2>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>To provide and maintain our clinical documentation service</li>
            <li>To process and transcribe audio recordings</li>
            <li>To generate AI-powered clinical notes</li>
            <li>To integrate with your Electronic Medical Record (EMR) system</li>
            <li>To process payments and manage your subscription</li>
            <li>To provide customer support through our in-app ticketing system</li>
            <li>To improve our AI models and service quality (using de-identified data only)</li>
            <li>To send important service updates and notifications</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Data Security</h2>
          <p className="mb-4">
            We implement industry-leading security measures to protect your data:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>AES-256 encryption for all data at rest</li>
            <li>TLS 1.3 encryption for all data in transit</li>
            <li>SOC 2 Type II compliant infrastructure</li>
            <li>Regular security audits and penetration testing</li>
            <li>Role-based access controls</li>
            <li>Automatic session timeouts</li>
            <li>Multi-factor authentication support</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">HIPAA Compliance</h2>
          <p className="mb-4">
            Grail is designed to be HIPAA compliant. We:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>Execute Business Associate Agreements (BAAs) with covered entities</li>
            <li>Implement required administrative, physical, and technical safeguards</li>
            <li>Train all employees on HIPAA requirements</li>
            <li>Maintain audit logs of all PHI access</li>
            <li>Have breach notification procedures in place</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Data Retention</h2>
          <p className="mb-4">
            We retain your account information and generated notes for as long as your account is active. Audio recordings are processed in real-time and deleted immediately after transcription unless you choose to save them. Upon account termination, we will delete or de-identify your data within 30 days, unless required to retain it for legal purposes.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Third-Party Services</h2>
          <p className="mb-4">
            We use carefully selected third-party services to provide our platform:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>Cloud infrastructure providers (with BAAs in place)</li>
            <li>AI model providers for note generation</li>
            <li>Payment processors for subscription billing</li>
            <li>EMR integration partners</li>
          </ul>
          <p className="mb-4">
            All third-party providers are vetted for security and HIPAA compliance where applicable.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Your Rights</h2>
          <p className="mb-4">
            You have the right to:
          </p>
          <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>Access your personal data and generated notes</li>
            <li>Export your data in a portable format</li>
            <li>Request correction of inaccurate data</li>
            <li>Request deletion of your data</li>
            <li>Opt out of non-essential communications</li>
          </ul>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Changes to This Policy</h2>
          <p className="mb-4">
            We may update this Privacy Policy from time to time. We will notify you of any material changes by posting the new policy on this page and updating the &quot;Last updated&quot; date. Your continued use of the service after changes constitutes acceptance of the updated policy.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">Contact Us</h2>
          <p className="mb-4">
            For privacy-related questions or concerns, please submit a support ticket through the app or use our{" "}
            <Link href="/contact" className="text-primary hover:underline">
              contact form
            </Link>.
          </p>
          <p className="text-muted-foreground">
            Pound of Cure LLC<br />
            Write Great Notes
          </p>
        </section>
      </div>
    </div>
  );
}
