"use client"

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogDescription,
  DialogClose,
} from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { FileText, Sparkles, X } from "lucide-react"

interface SampleNoteModalProps {
  trigger?: React.ReactNode
}

export function SampleNoteModal({ trigger }: SampleNoteModalProps) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        {trigger || (
          <Button variant="outline" size="lg" className="gap-2">
            <FileText className="h-5 w-5" />
            See a Real AI-Generated Note
          </Button>
        )}
      </DialogTrigger>
      <DialogContent className="max-w-5xl max-h-[90vh] p-0">
        {/* Fixed Header */}
        <div className="sticky top-0 z-10 bg-background border-b p-6 pb-4">
          <DialogClose className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-accent data-[state=open]:text-muted-foreground">
            <X className="h-5 w-5" />
            <span className="sr-only">Close</span>
          </DialogClose>

          <DialogHeader>
            <div className="flex items-center gap-3 mb-2 pr-8">
              <div className="h-10 w-10 rounded-full bg-primary/10 flex items-center justify-center flex-shrink-0">
                <Sparkles className="h-5 w-5 text-primary" />
              </div>
              <div>
                <DialogTitle className="text-2xl">Real AI-Generated Clinical Note</DialogTitle>
                <DialogDescription className="text-base mt-1">
                  100% generated by Grail from a patient conversation. Zero edits by the provider.
                </DialogDescription>
              </div>
            </div>
            <div className="bg-success/10 border border-success/30 rounded-lg p-4 mt-4">
              <p className="text-sm text-success font-medium">
                This is an actual note generated by our AI scribe. The provider simply talked to their patient, the conversation was transcribed, and this comprehensive clinical note was automatically generated. No additional editing or changes were made.
              </p>
            </div>
          </DialogHeader>
        </div>

        {/* Scrollable Content */}
        <div className="overflow-y-auto p-6 pt-4">
          <div className="prose prose-sm dark:prose-invert max-w-none">
            <div className="bg-muted/30 rounded-lg p-6 text-sm leading-relaxed space-y-6">

              <section>
                <h3 className="text-lg font-bold text-foreground mb-2 font-sans">Brief Summary</h3>
                <p className="text-muted-foreground">
                  59-year-old woman with severe GERD symptoms from a large hiatal hernia and biopsy-proven eosinophilic esophagitis seen by Dr. Martinez for bariatric surgery evaluation and symptom management, with focus on medical optimization and anticoagulation prior to planned gastric bypass with concurrent hiatal hernia repair.
                </p>
              </section>

              <section>
                <h3 className="text-lg font-bold text-foreground mb-2 font-sans">Chief Complaint</h3>
                <p className="text-muted-foreground">
                  Patient presents for bariatric surgery follow-up with Dr. Martinez to address severe reflux and obstructive symptoms from a large hiatal hernia, review biopsy results showing eosinophilic esophagitis, and discuss preoperative optimization and medical management while awaiting gastric bypass with hernia repair.
                </p>
              </section>

              <section>
                <h3 className="text-lg font-bold text-foreground mb-2 font-sans">History of Present Illness</h3>
                <div className="text-muted-foreground space-y-3">
                  <p><strong>Initiation/Current AOM:</strong> On tirzepatide (Zepbound) 15 mg subcutaneous weekly prior to this visit as part of the bariatric program; continued at same dose today (no titration changes discussed this visit).</p>
                  <p><strong>Weight trajectory:</strong> Weight decreased from 310 lb at initial bariatric intake to 297 lb at today&apos;s visit (down ~13 lb, ~4% of body weight), partially intentional via diet changes and partially due to poor tolerance of solid foods.</p>
                  <p><strong>GI symptom chronology:</strong> Over recent weeks, reports &quot;if I eat a couple bites I feel like I am stuffed and it&apos;s just sitting right here&quot; with persistent sensation from prior-day meals, consistent with severe early satiety and dysphagia in the setting of a large hiatal hernia.</p>
                  <p><strong>Biopsy results:</strong> Recent upper endoscopy biopsies show eosinophilic esophagitis; Dr. Martinez suspects this is primarily secondary to chronic acid reflux from the large hiatal hernia, with possible contribution from food allergy.</p>
                  <p><strong>Adverse symptoms:</strong> Ongoing bothersome heartburn/acid reflux, chest/epigastric pressure after small amounts of food, and inability to tolerate normal portions; denies use of acid blockers prior to this visit despite severe symptoms.</p>
                  <p><strong>Impact on intake and weight:</strong> Markedly reduced oral intake due to discomfort and early satiety, contributing to unintentional component of weight loss; patient has also intentionally increased vegetables and cut all sugar out.</p>
                  <p><strong>Surgical planning counseling:</strong> Extensive counseling that isolated hiatal hernia repair would be unsafe and ineffective, with high risk of recurrence and loss of bariatric surgery eligibility; emphasized need for a single, properly performed gastric bypass with concurrent hiatal hernia repair at Valley Medical Center once medically optimized.</p>
                  <p><strong>Anticoagulation/medical optimization:</strong> History of two prior blood clots and supposed need for chronic warfarin, but currently off anticoagulation due to lack of primary care management; Dr. Martinez expresses concern that surgery is unsafe until anticoagulation is appropriately managed and overall medical status optimized.</p>
                  <p><strong>Interim medical therapy:</strong> Today, started on swallowed budesonide-formoterol HFA inhaler (2 puffs twice daily, swallow not inhale) as topical steroid for eosinophilic esophagitis, pantoprazole as a proton pump inhibitor, sucralfate (Carafate) slurry for esophageal coating, and hyoscyamine sublingual as needed for esophageal spasm/tightness around meals.</p>
                  <p><strong>Anticoagulation bridge:</strong> Due to high thrombotic risk and current absence of warfarin management, Dr. Martinez initiates enoxaparin (Lovenox) injections for ~1 month as temporary prophylaxis while the patient transitions primary care.</p>
                  <p><strong>Primary care transition:</strong> Strongly advised to switch primary care from current clinic to Community Health Center so that a dedicated primary care team and pharmacist can manage warfarin and optimize chronic conditions before surgery; patient agrees to contact her insurance and the health center to initiate transfer.</p>
                  <p><strong>Follow-up planning:</strong> Will meet with bariatric coordinator (Sarah) to clarify remaining preoperative steps and scheduling timeline; surgery deferred until anticoagulation and primary care issues are resolved.</p>
                </div>
              </section>

              <section>
                <h3 className="text-lg font-bold text-foreground mb-2 font-sans">Obesity Specific History</h3>
                <div className="text-muted-foreground space-y-3">
                  <p><strong>Height/Weight/BMI:</strong> Most recent documented weights 310 lb (prior visit) and 297 lb today; BMI not recorded but patient meets criteria for class 3 obesity and is in a bariatric surgery program.</p>
                  <p><strong>Medication-Assisted Weight Loss:</strong> On tirzepatide (Zepbound) 15 mg subcutaneous once weekly with ongoing use; weight loss to date (~13 lb) is a mix of intentional changes and decreased intake from GI symptoms.</p>
                  <p><strong>Exercise:</strong> No specific exercise regimen discussed at this visit; functional capacity appears preserved aside from limitations related to discomfort with eating.</p>
                  <p><strong>Nutrition/Hydration:</strong> Reports doing &quot;the thing with the vegetables&quot; and having cut all sugar out; currently limited to very small portions due to early satiety and chest/epigastric fullness, raising concern for inadequate protein and calories.</p>
                  <p><strong>Prior AOMs/Bariatric History:</strong> Currently in a bariatric program with planned gastric bypass (RYGB) and concurrent hiatal hernia repair; no prior bariatric surgery mentioned.</p>
                  <p><strong>Obesity-Related Symptoms:</strong> Significant reflux and dysphagia from large hiatal hernia and eosinophilic esophagitis, impacting intake and contributing to weight loss.</p>
                </div>
              </section>

              <section>
                <h3 className="text-lg font-bold text-foreground mb-2 font-sans">Past Medical History</h3>
                <div className="text-muted-foreground">
                  <p className="font-semibold mt-2">Obesity-Related Conditions:</p>
                  <ul className="list-disc list-inside ml-4">
                    <li>Class 3 obesity in bariatric surgery program</li>
                    <li>Arthritis (chronic joint pain; details not specified)</li>
                    <li>Gastroesophageal reflux disease with large hiatal hernia</li>
                  </ul>
                  <p className="font-semibold mt-3">Other Medical Conditions:</p>
                  <ul className="list-disc list-inside ml-4">
                    <li>Eosinophilic esophagitis on recent biopsy</li>
                    <li>History of blood clots (two prior events; supposed to be on chronic warfarin)</li>
                    <li>Depression</li>
                    <li>Anxiety</li>
                  </ul>
                </div>
              </section>

              <section>
                <h3 className="text-lg font-bold text-foreground mb-2 font-sans">Active Medications</h3>
                <ul className="list-disc list-inside text-muted-foreground ml-4 space-y-1">
                  <li>Budesonide-formoterol HFA 160 mcg-4.5 mcg/actuation aerosol inhaler — 2 puffs by mouth twice daily, swallow, do not inhale</li>
                  <li>Sucralfate 1 g tablet — 1 tablet orally four times daily; dissolve in 2–3 ounces of water for 5 minutes prior to taking</li>
                  <li>Hyoscyamine 0.125 mg sublingual tablet — 1 tablet sublingually every 4–6 hours as needed for esophageal spasm/tightness</li>
                  <li>Pantoprazole (Protonix) — oral proton pump inhibitor; dose and frequency not specified, initiated today for acid suppression</li>
                  <li>Enoxaparin (Lovenox) — subcutaneous injection; dose not specified, prescribed for approximately 1 month as interim anticoagulation</li>
                  <li>Gabapentin 300 mg capsule — 300 mg orally twice daily</li>
                  <li>Hydroxyzine HCl 10 mg tablet — 10 mg orally as needed</li>
                  <li>Ibuprofen 800 mg tablet — 800 mg orally as needed</li>
                  <li>Carbamazepine — reportedly 400 mg orally daily</li>
                  <li>Wellbutrin — oral formulation; dose not specified</li>
                  <li>Tirzepatide (Zepbound) VIAL 15 mg subcutaneous injection — 15 mg subcutaneously once weekly</li>
                </ul>
              </section>

              <section>
                <h3 className="text-lg font-bold text-foreground mb-2 font-sans">Allergies</h3>
                <p className="text-muted-foreground">No known medication allergies (NKMA).</p>
              </section>

              <section>
                <h3 className="text-lg font-bold text-foreground mb-2 font-sans">Family History</h3>
                <ul className="list-disc list-inside text-muted-foreground ml-4">
                  <li>Mother: Hiatal hernia (required surgical repair many years ago with large incision)</li>
                  <li>Older sister: Hiatal hernia</li>
                </ul>
              </section>

              <section>
                <h3 className="text-lg font-bold text-foreground mb-2 font-sans">Social History</h3>
                <ul className="list-disc list-inside text-muted-foreground ml-4">
                  <li>Marital Status: Married</li>
                  <li>Employment: Full-time student</li>
                  <li>Tobacco Use: Never smoked or vaped</li>
                  <li>Alcohol Use: A few times a month</li>
                  <li>Cannabis Use: A few times a year at most</li>
                  <li>Substance Use: Denies regular use of illicit drugs</li>
                </ul>
              </section>

              <section>
                <h3 className="text-lg font-bold text-foreground mb-2 font-sans">Review of Systems</h3>
                <div className="text-muted-foreground space-y-1">
                  <p><strong>CONSTITUTIONAL:</strong> unintentional and intentional weight loss since last visit, no fever/chills, no fatigue</p>
                  <p><strong>CARDIOVASCULAR:</strong> no chest pain, no palpitations, no edema</p>
                  <p><strong>RESPIRATORY:</strong> no dyspnea, no wheeze, no cough</p>
                  <p><strong>GASTROINTESTINAL:</strong> heartburn/GERD symptoms (bothersome); dysphagia and early satiety present, no nausea, no vomiting, no abdominal pain, normal bowel habits</p>
                  <p><strong>GENITOURINARY:</strong> no dysuria, frequency, urgency, or hematuria</p>
                  <p><strong>MUSCULOSKELETAL:</strong> no new joint pain or weakness</p>
                  <p><strong>SKIN:</strong> redundant/lax skin after weight loss, no rashes or lesions</p>
                  <p><strong>NEUROLOGICAL:</strong> no headaches, syncope, weakness, numbness, or speech changes</p>
                  <p><strong>ENDOCRINE:</strong> no heat/cold intolerance, no polyuria/polydipsia</p>
                  <p><strong>HEMATOLOGIC/LYMPHATIC:</strong> no easy bruising or bleeding, no lymphadenopathy</p>
                  <p><strong>PSYCHIATRIC:</strong> normal mood, no depression or anxiety reported</p>
                </div>
              </section>

              <section>
                <h3 className="text-lg font-bold text-foreground mb-2 font-sans">Vitals</h3>
                <ul className="list-disc list-inside text-muted-foreground ml-4">
                  <li>Weight (prior visit): 310 lb</li>
                  <li>Weight (current visit): 297 lb</li>
                </ul>
              </section>

              <section>
                <h3 className="text-lg font-bold text-foreground mb-2 font-sans">Physical Examination</h3>
                <div className="text-muted-foreground space-y-1">
                  <p><strong>General Appearance:</strong> Alert and oriented, healthy-appearing, overweight, and in no acute distress.</p>
                  <p><strong>Head:</strong> Normocephalic, atraumatic.</p>
                  <p><strong>Lungs:</strong> Respirations unlabored; no dyspnea observed.</p>
                  <p><strong>Musculoskeletal:</strong> Ambulates within normal limits; normal motor strength and tone.</p>
                  <p><strong>Psychiatric:</strong> Good judgment and insight; normal mood and affect; oriented to person, time, and place.</p>
                </div>
              </section>

              <section>
                <h3 className="text-lg font-bold text-foreground mb-2 font-sans">Assessment Notes</h3>
                <div className="text-muted-foreground space-y-3">
                  <p><strong>Class 3 obesity:</strong> Engaged in bariatric program with tirzepatide (Zepbound) and lifestyle changes; modest ~13 lb loss to date, partly limited by pathologic reduction in intake from GI disease; appropriate candidate for RYGB with concurrent hiatal hernia repair once medically optimized.</p>
                  <p><strong>Gastroesophageal reflux disease with large hiatal hernia:</strong> Severe, refractory symptoms with early satiety and chest/epigastric fullness; likely driving eosinophilic esophagitis and weight loss; definitive management requires gastric bypass with hiatal hernia repair rather than isolated hernia surgery.</p>
                  <p><strong>Eosinophilic esophagitis:</strong> Biopsy-proven; suspected primarily secondary to acid reflux with possible food allergy contribution; initiating swallowed topical steroid and aggressive acid suppression.</p>
                  <p><strong>Dysphagia and early satiety with epigastric discomfort:</strong> Likely multifactorial from large hiatal hernia and eosinophilic esophagitis; currently causing significant functional limitation and contributing to reduced oral intake and weight loss.</p>
                  <p><strong>History of blood clots (needs chronic anticoagulation):</strong> High thrombotic risk with two prior events; currently not on warfarin due to lack of management; surgery deemed unsafe until anticoagulation is appropriately overseen by primary care; started temporary enoxaparin as bridge.</p>
                  <p><strong>Depression and anxiety:</strong> Longstanding, managed with Wellbutrin, carbamazepine, gabapentin, and hydroxyzine; appear stable and not a barrier to surgery, but require continuity of care.</p>
                  <p><strong>Arthritis:</strong> Chronic, obesity-related joint pain; not specifically limiting current bariatric or surgical plans.</p>
                  <p><strong>Primary care gaps:</strong> Current primary care not adequately managing complex medical issues (anticoagulation, GERD); strong recommendation to transition to Community Health Center for comprehensive management before proceeding to surgery.</p>
                </div>
              </section>

              <section>
                <h3 className="text-lg font-bold text-foreground mb-2 font-sans">Treatment Notes</h3>
                <div className="text-muted-foreground space-y-2">
                  <p><strong>Bariatric surgery:</strong> Plan for gastric bypass (RYGB) with concurrent hiatal hernia repair at Valley Medical Center once medically optimized and anticoagulation is stable; avoid isolated hiatal hernia repair by non-bariatric surgeons due to high recurrence and risk.</p>
                  <p><strong>Nutrition:</strong> Continue focus on vegetables and avoidance of added sugars while monitoring for adequate overall intake; encourage small, frequent, soft-textured meals to minimize dysphagia and reflux.</p>
                  <p><strong>Symptom management:</strong> Use swallowed topical steroid (budesonide-formoterol HFA), pantoprazole, sucralfate, and hyoscyamine before meals as directed to reduce inflammation, acid exposure, and esophageal spasm.</p>
                  <p><strong>Anticoagulation/medical optimization:</strong> Begin enoxaparin (Lovenox) injections as interim prophylaxis; urgently establish care at Community Health Center for long-term warfarin or other anticoagulation management and overall preoperative clearance.</p>
                  <p><strong>Care coordination:</strong> Patient to contact insurance and Community Health Center to switch primary care, then work with bariatric coordinator (Sarah) to complete remaining preoperative steps and plan surgical timing.</p>
                  <p><strong>Follow-up expectations:</strong> Continue bariatric program and medication regimen; surgery scheduling to proceed only once primary care and anticoagulation management are in place.</p>
                </div>
              </section>

              <section>
                <h3 className="text-lg font-bold text-foreground mb-2 font-sans">Patient Instructions</h3>
                <ol className="list-decimal list-inside text-muted-foreground ml-4 space-y-2">
                  <li>Use the steroid inhaler exactly as directed: take 2 puffs into your mouth twice a day and swallow instead of inhaling.</li>
                  <li>Take your pantoprazole once daily on an empty stomach, about 30–60 minutes before your first meal.</li>
                  <li>Prepare sucralfate 1 g by dissolving it in 2–3 ounces of water, letting it sit ~5 minutes, then drink it on an empty stomach and away from other medications.</li>
                  <li>Use hyoscyamine 0.125 mg under your tongue before meals or when you feel spasm/tightness, up to every 4–6 hours as needed.</li>
                  <li>Give yourself enoxaparin (Lovenox) injections daily as prescribed, rotating injection sites; call the clinic or seek urgent care if you notice heavy bleeding, large unexplained bruises, chest pain, or sudden shortness of breath.</li>
                  <li>Continue your Zepbound 15 mg injection once a week on the same day each week; contact the clinic if you are unable to maintain adequate food or fluid intake.</li>
                  <li>Eat small, soft, frequent meals, focus on vegetables and protein, and avoid added sugars as you have been doing.</li>
                  <li>Call your insurance and Community Health Center today to switch your primary care and schedule a visit for anticoagulation and overall medical management.</li>
                  <li>Meet with Sarah from the bariatric team to review remaining preoperative steps and surgery planning.</li>
                  <li>Go to the ER or call 911 for severe chest pain, trouble breathing, signs of a blood clot (leg swelling, chest pain, sudden shortness of breath), or inability to swallow liquids.</li>
                </ol>
              </section>

              <section>
                <h3 className="text-lg font-bold text-foreground mb-2 font-sans">Follow Up</h3>
                <p className="text-muted-foreground">
                  Follow up with Dr. Martinez and the bariatric surgery team, including Sarah, after establishing care with Community Health Center primary care and initiating long-term anticoagulation management.
                </p>
              </section>

            </div>
          </div>

          <div className="border-t pt-4 mt-6">
            <div className="bg-primary/10 rounded-lg p-4 text-center">
              <p className="text-sm text-muted-foreground mb-2">
                This comprehensive note was generated in seconds from a natural patient conversation.
              </p>
              <p className="text-primary font-semibold">
                No templates. No checkboxes. Just great clinical documentation.
              </p>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
